"""Write verification/export-report.md from manifest.json and
region-assignment.csv - the human-readable record of what was built.

    python tools/export_report.py [--manifest manifest.json]
        [--assignment region-assignment.csv] [--inventory inventory.csv]
        [--out verification/export-report.md]

Pure Python. Everything in the report is read from the committed records, so
it can be regenerated without Blender and without the .glb files.
"""

import argparse
import csv
import json
import os
import sys
from collections import Counter, defaultdict

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
import regions  # noqa: E402
import scope  # noqa: E402

# The indicative bands from the brief (centroid height, base-mesh triangles).
BRIEF_BANDS = [
    ("head-jaw + cervical", ["head-jaw", "cervical"], 560207, 280000),
    ("shoulder", ["shoulder"], 506963, 253000),
    ("thoracic", ["thoracic"], 620502, 310000),
    ("elbow-wrist", ["elbow-wrist"], 360891, 180000),
    ("lumbar", ["lumbar"], 193956, 97000),
    ("hip", ["hip"], 411460, 206000),
    ("knee", ["knee"], 39090, 20000),
    ("ankle-foot", ["ankle-foot"], 266714, 133000),
]


def fmt(n):
    return "{:,}".format(n)


def mb(b):
    return "%.2f MB" % (b / 1e6)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", default="manifest.json")
    ap.add_argument("--assignment", default="region-assignment.csv")
    ap.add_argument("--inventory", default="inventory.csv")
    ap.add_argument("--out", default=os.path.join("verification", "export-report.md"))
    args = ap.parse_args()

    m = json.load(open(args.manifest, encoding="utf-8"))
    rows = list(csv.DictReader(open(args.assignment, encoding="utf-8")))
    inv = regions.load_inventory(args.inventory)
    kept, excluded, report = scope.partition(inv)
    src = m["source"]

    L = []
    w = L.append
    w("# Mesh export report")
    w("")
    w("Generated by `tools/export_report.py` from `manifest.json` and "
      "`region-assignment.csv`. Blender %s, `%s`." % (src["blender"], src["model"]))
    w("")

    # ---- 1. kept counts ----------------------------------------------------
    w("## 1. Kept counts against the brief")
    w("")
    w("| Step | Meshes | Triangles |")
    w("|---|---:|---:|")
    w("| Scope filter (collections 1-4, labels dropped) | %s | %s |" % (
        fmt(src["inventoryMeshes"]), fmt(src["inventoryTriangles"])))
    w("| Brief §1 | 2,060 | 2,959,783 |")
    w("| Licence filter (EXCLUSIONS.md) removed | %d | %s |" % (
        len(src["licenceExcluded"]), fmt(src["licenceExcludedTriangles"])))
    w("| Kept, inventory (base-mesh) triangles | %s | %s |" % (
        fmt(src["keptMeshes"]), fmt(src["keptInventoryTriangles"])))
    w("| Kept, exported source (modifiers applied, see §6) | %s | %s |" % (
        fmt(src["keptMeshes"]), fmt(src["keptSourceTriangles"])))
    w("")
    w("Exclusions asserted on the full inventory: " + ", ".join(
        "%s %d/%d/%d" % (k, c["objects"], c["with_geometry"], c["triangles"])
        for k, c in report["exclusion_counts"].items()) + " (objects / with geometry / triangles), "
      "all equal to `EXPECTED`.")
    w("")
    w("Of the %d excludable meshes with geometry, **%d were already outside scope** and "
      "**%d were removed by the licence filter itself**: %s. The filter is not inert on "
      "this scope - the auditory ossicles are filed under the skeletal system." % (
          report["excludable_with_geometry"], report["caught_by_scope"],
          report["caught_by_licence_filter"], ", ".join(src["licenceExcluded"])))
    w("")
    w("| System | Meshes | Inventory triangles | Exported source triangles |")
    w("|---|---:|---:|---:|")
    for sy, p in src["perSystem"].items():
        w("| %s | %s | %s | %s |" % (sy, fmt(p["meshes"]), fmt(p["inventoryTriangles"]), fmt(p["sourceTriangles"])))
    w("")

    # ---- 2. region assignment -----------------------------------------------
    w("## 2. Region assignment")
    w("")
    w("Signals, in precedence order: `override` (the clinical table at the top of "
      "`tools/regions.py`), `hierarchy` (Bonus collection anatomy and Main divisions, "
      "side words stripped), `parent` (an insertion follows its muscle), `pairing` "
      "(a side inherits its twin), `centroid` (height bands, fallback only).")
    w("")
    per = defaultdict(lambda: {"n": 0, "tris": 0, "l": 0, "r": 0, "": 0, "sig": Counter(),
                               "sys": Counter()})
    for r in rows:
        p = per[r["region"]]
        p["n"] += 1
        p["tris"] += int(r["triangles"])
        p[r["side"]] += 1
        p["sig"][r["signal"]] += 1
        p["sys"][r["system"]] += 1
    w("| Region | Meshes | Inventory tris | .l | .r | midline | skel / musc / artic / insert | override | hierarchy | parent | pairing | centroid |")
    w("|---|---:|---:|---:|---:|---:|---|---:|---:|---:|---:|---:|")
    for rg in regions.REGIONS:
        p = per[rg]
        w("| %s | %d | %s | %d | %d | %d | %d / %d / %d / %d | %d | %d | %d | %d | %d |" % (
            rg, p["n"], fmt(p["tris"]), p["l"], p["r"], p[""],
            p["sys"]["skeletal"], p["sys"]["muscular"], p["sys"]["articular"], p["sys"]["insertion"],
            p["sig"]["override"], p["sig"]["hierarchy"], p["sig"]["parent"],
            p["sig"]["pairing"] + p["sig"]["pairing-conflict"], p["sig"]["centroid"]))
    w("")
    names = {r["sourceName"] for r in rows}
    unpaired = sorted(n for n in names if scope.twin_of(n) and scope.twin_of(n) not in names)
    w("`.l` and `.r` differ where the atlas itself is one-sided. The %d unpaired objects, "
      "all upstream:" % len(unpaired))
    w("")
    byreg = defaultdict(list)
    for n in unpaired:
        byreg[next(r["region"] for r in rows if r["sourceName"] == n)].append(n)
    for rg in regions.REGIONS:
        if byreg[rg]:
            w("- **%s**: %s" % (rg, ", ".join("`%s`" % n for n in byreg[rg])))
    w("")
    w("### Assigned by centroid alone")
    w("")
    w("The set to eyeball. One line per object, both sides folded; `tris` is the "
      "inventory count of one side.")
    w("")
    w("| Region | System | Tris | Object | Centroid |")
    w("|---|---|---:|---|---|")
    seen = set()
    for r in sorted(rows, key=lambda r: (regions.REGIONS.index(r["region"]), r["sourceName"])):
        if r["signal"] != "centroid":
            continue
        b = scope.base_name(r["sourceName"])
        if b in seen:
            continue
        seen.add(b)
        w("| %s | %s | %s | %s | %s |" % (r["region"], r["system"], r["triangles"], b, r["detail"]))
    w("")
    conflicts = [r for r in rows if r["signal"] == "pairing-conflict"]
    if conflicts:
        w("### Twins the signals disagreed on")
        w("")
        for r in conflicts:
            w("- `%s` -> %s (%s)" % (r["sourceName"], r["region"], r["detail"]))
        w("")

    # ---- 3. actual vs target ---------------------------------------------------
    w("## 3. Triangles: actual against target")
    w("")
    w("Per region as assigned. `Source` is the exported source (modifiers applied); "
      "`target` is 50% of it; `own` is what the file holds for the region's own meshes; "
      "`context` is the neighbours at 12.5% of their source.")
    w("")
    w("| Region | Meshes | Inventory | Source | Target (50%) | Own exported | vs target | Context meshes | Context tris | File total |")
    w("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    regs = {r["id"]: r for r in m["regions"]}
    for rg in regions.REGIONS:
        r = regs.get(rg)
        if not r:
            continue
        w("| %s | %d | %s | %s | %s | %s | %+.1f%% | %d | %s | %s |" % (
            rg, r["meshCount"], fmt(r["inventoryTriangles"]), fmt(r["sourceTriangles"]),
            fmt(r["targetTriangles"]), fmt(r["ownTriangles"]),
            100.0 * (r["ownTriangles"] - r["targetTriangles"]) / max(r["targetTriangles"], 1),
            r["contextMeshCount"], fmt(r["contextTriangles"]), fmt(r["triangles"])))
    w("")
    w("Against the brief's indicative bands (centroid height, base-mesh counts), "
      "using inventory triangles of the assigned regions so the comparison is like for like:")
    w("")
    w("| Band | Brief source | Brief target | Assigned inventory tris | Assigned source tris | Own exported |")
    w("|---|---:|---:|---:|---:|---:|")
    for label, ids, bsrc, btgt in BRIEF_BANDS:
        inv_t = sum(regs[i]["inventoryTriangles"] for i in ids if i in regs)
        src_t = sum(regs[i]["sourceTriangles"] for i in ids if i in regs)
        own_t = sum(regs[i]["ownTriangles"] for i in ids if i in regs)
        w("| %s | %s | %s | %s | %s | %s |" % (label, fmt(bsrc), fmt(btgt), fmt(inv_t), fmt(src_t), fmt(own_t)))
    w("")
    if m.get("overview"):
        o = m["overview"]
        w("**Overview**: %d meshes, %s triangles against a target of %s (ratio %.4f, floor %d "
          "triangles per mesh), %s. Insertions are not in it." % (
              o["meshCount"], fmt(o["triangles"]), fmt(o["target"]), o["ratio"],
              m["decimation"]["floors"]["overview"], mb(o["bytes"])))
        w("")

    # ---- 4. decimation quality ---------------------------------------------------
    w("## 4. Decimation quality")
    w("")
    w("Blender Decimate, COLLAPSE, triangulated. Deviation is the nearest-surface "
      "distance from every decimated vertex back to the source mesh, per object, "
      "in millimetres; `max/diag` is the worst vertex relative to the object's "
      "bounding-box diagonal. Visual checks are in `verification/decimation/`.")
    w("")
    dev = m["decimation"].get("deviation", {})
    for tier in ("region", "context", "overview"):
        if tier not in dev:
            continue
        w("### %s tier (%s)" % (tier, {"region": "50%", "context": "12.5%",
                                        "overview": "%.1f%%" % (100 * m["decimation"]["overviewRatio"])}[tier]))
        w("")
        w("| System | Meshes decimated | Mean of mean | Mean of p95 | Mean of max | Worst max |")
        w("|---|---:|---:|---:|---:|---:|")
        for sy, d in dev[tier].items():
            w("| %s | %d | %.3f mm | %.3f mm | %.3f mm | %.2f mm |" % (
                sy, d["meshes"], d["meanOfMean_mm"], d["meanOfP95_mm"], d["meanOfMax_mm"], d["worstMax_mm"]))
        w("")
        w("Worst relative to object size:")
        w("")
        for sy, d in dev[tier].items():
            for x in d["worstRelative"][:3]:
                w("- %s `%s`: max %.2f mm, %.1f%% of diagonal" % (
                    sy, x["sourceName"], x["max_mm"], 100 * x["maxOverDiagonal"]))
        w("")

    raised = m["decimation"].get("ratioRaised", [])
    w("### Meshes the ratio was raised for")
    w("")
    w("Any mesh whose decimated surface drifted more than %d%% of its own diagonal was "
      "re-decimated at 75%%, then kept at source if that still drifted. %d decimations "
      "retreated, on %d distinct objects:" % (
          round(100 * m["decimation"]["maxDriftOfDiagonal"]), len(raised),
          len({r["sourceName"] for r in raised})))
    w("")
    if raised:
        w("| Object | System | Tier | From | To | Triangles kept |")
        w("|---|---|---|---:|---:|---:|")
        for r in sorted(raised, key=lambda r: (r["sourceName"], r["tier"])):
            w("| %s | %s | %s | %.1f%% | %.0f%% | %d |" % (
                r["sourceName"], r["system"], r["tier"], 100 * r["from"], 100 * r["to"], r["triangles"]))
    w("")
    w("No whole class of mesh degraded at 50%: the retreats are individual objects "
      "with thin or spiky geometry (the body of the sternum, one lumbar vertebra, the "
      "transverse ligament of the knee, the medial intermuscular septum of the arm), "
      "so the 50% ratio was held for every class and these were handled per object.")
    w("")

    # ---- 5. bytes ---------------------------------------------------------------------
    w("## 5. Exported bytes")
    w("")
    w("| File | Triangles | Bytes | Insertion layer | Insertion tris | Insertion bytes |")
    w("|---|---:|---:|---|---:|---:|")
    total = 0
    if m.get("overview"):
        o = m["overview"]
        w("| overview.glb | %s | %s | | | |" % (fmt(o["triangles"]), mb(o["bytes"])))
        total += o["bytes"]
    for rg in regions.REGIONS:
        r = regs.get(rg)
        if not r:
            continue
        i = r["insertionLayer"]
        w("| %s | %s | %s | %s | %s | %s |" % (
            r["file"], fmt(r["triangles"]), mb(r["bytes"]), i["file"], fmt(i["triangles"]), mb(i["bytes"])))
        total += r["bytes"] + i["bytes"]
    w("| **total** | | **%s** | | | |" % mb(total))
    w("")
    w("Draco-compressed, with normals and UVs, atlas materials without textures. "
      "`.glb` files are built locally and gitignored.")
    w("")

    # ---- 6. surprises --------------------------------------------------------------
    g = m["geometry"]
    w("## 6. What the model did that the inventory did not predict")
    w("")
    w("- **Mirroring by negative scale, with shared mesh data.** Twin pairs: %s. "
      "The `.l` side of a mirror-instance pair is the same datablock as the `.r` "
      "side under a reflecting transform. Every object is baked to world space and "
      "the winding reversed where the determinant is negative, so every exported "
      "node has an identity transform and outward normals on both sides. Decimation "
      "runs once per datablock and is baked twice." % ", ".join(
          "%s %d" % kv for kv in sorted(g["mirrorPairs"].items())))
    w("- **Modifiers.** %s. The base meshes the inventory counted are cages for most "
      "ligaments: the anterior talofibular ligament is two triangles before its "
      "Subdivision and Solidify run. Skeletal, muscular and articular objects are "
      "therefore exported from their viewport-evaluated mesh (%s -> %s triangles). "
      "Insertions are the exception and stay as flat base-mesh patches at full "
      "resolution (their modifiers would take 63,843 triangles to 931,484 for a "
      "0.5 mm skin); a viewer should draw the insertion layer with a small depth "
      "offset." % (
          ", ".join("%s %d" % kv for kv in sorted(g["modifiersApplied"].items())),
          fmt(src["keptInventoryTriangles"]), fmt(src["keptSourceTriangles"])))
    w("- **Inside-out source meshes.** %d closed objects had negative signed volume "
      "after the bake, i.e. inward-facing winding in the atlas itself, on both "
      "sides. They were flipped: %s." % (
          len(g["windingCorrected"]),
          ", ".join("`%s`" % n for n in g["windingCorrected"]) or "none"))
    w("- **One-sided objects.** %d objects have no contralateral twin (listed in §2), "
      "24 of them insertion footprints painted on one side only." % len(unpaired))
    w("- **Upstream side tags are wrong as well as incomplete.** Left tarsal bones "
      "are filed under `Right foot`. Division tags are used with the side word "
      "stripped; the side comes only from the name suffix.")
    w("- **The exporter drops a few degenerate triangles.** Manifest counts are "
      "read back from each file's index accessors, not from the meshes handed to "
      "the exporter, so they are what a viewer will load.")
    w("")

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print("REPORT_OK out=%s" % args.out)


if __name__ == "__main__":
    main()
